package org.jmixworkbench.generator

import org.jmixworkbench.model.ScenarioActorMode
import org.jmixworkbench.model.ScenarioAssertionOperator
import org.jmixworkbench.model.ScenarioStepKind
import org.jmixworkbench.model.ScenarioStepModel
import org.jmixworkbench.model.ScenarioTestModel
import org.jmixworkbench.model.ScenarioValueModel
import org.jmixworkbench.model.ScenarioValueType

/**
 * Generates an executable Jmix/Spring Boot integration test from a visual business scenario.
 *
 * The generated test deliberately uses stable public Jmix APIs: DataManager, EntityValues and
 * SystemAuthenticator. Reflection is limited to invoking the explicitly selected Spring bean
 * method so scenarios can span arbitrary application services without generated compile-time
 * coupling to their signatures.
 */
object ScenarioTestGenerator {
    private const val MARKER_PREFIX = "// JVW-SCENARIO-MODEL: "

    fun generate(model: ScenarioTestModel, encodedModel: String): String {
        require(model.packageName.isNotBlank()) { "A package is required." }
        require(model.className.isNotBlank()) { "A test class name is required." }
        require(model.steps.isNotEmpty()) { "At least one scenario step is required." }

        return buildString {
            append("package ").append(model.packageName).append(";\n\n")
            append("import io.jmix.core.DataManager;\n")
            append("import io.jmix.core.entity.EntityValues;\n")
            append("import io.jmix.core.security.SystemAuthenticator;\n")
            append("import org.junit.jupiter.api.AfterEach;\n")
            append("import org.junit.jupiter.api.Test;\n")
            append("import org.springframework.beans.factory.annotation.Autowired;\n")
            append("import org.springframework.boot.test.context.SpringBootTest;\n")
            append("import org.springframework.context.ApplicationContext;\n\n")
            append("import java.lang.reflect.InvocationTargetException;\n")
            append("import java.lang.reflect.Method;\n")
            append("import java.math.BigDecimal;\n")
            append("import java.time.Instant;\n")
            append("import java.time.LocalDate;\n")
            append("import java.time.LocalDateTime;\n")
            append("import java.time.OffsetDateTime;\n")
            append("import java.util.ArrayList;\n")
            append("import java.util.Collection;\n")
            append("import java.util.LinkedHashMap;\n")
            append("import java.util.List;\n")
            append("import java.util.Map;\n")
            append("import java.util.UUID;\n\n")
            append("import static org.assertj.core.api.Assertions.assertThat;\n")
            append("import static org.assertj.core.api.Assertions.fail;\n\n")
            if (encodedModel.isNotBlank()) {
                append(MARKER_PREFIX).append(encodedModel).append('\n')
            }
            append("/**\n")
            append(" * ").append(safeComment(model.name)).append('\n')
            if (model.description.isNotBlank()) {
                append(" * ").append(safeComment(model.description)).append('\n')
            }
            append(" * Generated by Jmix Visual Workbench. Review the preview before applying changes.\n")
            append(" */\n")
            append("@SpringBootTest\n")
            append("@SuppressWarnings({\"rawtypes\", \"unchecked\"})\n")
            append("class ").append(model.className).append(" {\n\n")
            append("    @Autowired\n")
            append("    DataManager dataManager;\n\n")
            append("    @Autowired\n")
            append("    ApplicationContext applicationContext;\n\n")
            append("    @Autowired\n")
            append("    SystemAuthenticator systemAuthenticator;\n\n")
            append("    private final Map<String, Object> variables = new LinkedHashMap<>();\n")
            append("    private final List<Object> createdEntities = new ArrayList<>();\n\n")
            append("    @Test\n")
            append("    void executeScenario() {\n")
            model.steps.forEachIndexed { index, step ->
                append("        // ").append(index + 1).append(". ").append(safeComment(step.label)).append('\n')
                append(renderStep(step))
                if (index != model.steps.lastIndex) append('\n')
            }
            append("    }\n\n")
            append(CLEANUP_AND_HELPERS)
            append("}\n")
        }
    }

    fun markerPrefix(): String = MARKER_PREFIX

    private fun renderStep(step: ScenarioStepModel): String =
        when (step.kind) {
            ScenarioStepKind.SEED_ENTITY -> renderSeed(step)
            ScenarioStepKind.INVOKE_SERVICE -> renderInvocation(step)
            ScenarioStepKind.ASSERT_PROPERTY -> renderPropertyAssertion(step)
            ScenarioStepKind.ASSERT_VALUE -> renderValueAssertion(step)
            ScenarioStepKind.ASSERT_ENTITY_COUNT -> renderEntityCount(step)
            ScenarioStepKind.ASSERT_SERVICE_FAILURE -> renderServiceFailureAssertion(step)
        }

    private fun renderSeed(step: ScenarioStepModel): String {
        val variable = requireNotNull(step.variableName)
        val entityClass = requireNotNull(step.entityClass)
        return buildString {
            append("        runAs(")
                .append(javaString(step.actorMode.name))
                .append(", ")
                .append(nullableJavaString(step.username))
                .append(", () -> {\n")
            append("            Object entity = dataManager.create((Class) loadClass(")
                .append(javaString(entityClass))
                .append("));\n")
            step.fields.forEach { field ->
                append("            EntityValues.setValue(entity, ")
                    .append(javaString(field.property))
                    .append(", ")
                    .append(renderValue(field.value))
                    .append(");\n")
            }
            append("            Object saved = dataManager.save(entity);\n")
            append("            createdEntities.add(saved);\n")
            append("            variables.put(").append(javaString(variable)).append(", saved);\n")
            append("            return saved;\n")
            append("        });\n")
        }
    }

    private fun renderInvocation(step: ScenarioStepModel): String {
        val args = step.arguments.joinToString(", ") { renderValue(it) }
        val invocation = "invokeBean(${javaString(requireNotNull(step.beanName))}, " +
            "${javaString(requireNotNull(step.methodName))}, new Object[]{$args})"
        val call = "runAs(${javaString(step.actorMode.name)}, ${nullableJavaString(step.username)}, () -> $invocation)"
        return if (step.resultVariable.isNullOrBlank()) {
            "        $call;\n"
        } else {
            buildString {
                append("        Object invocationResult = ").append(call).append(";\n")
                append("        variables.put(")
                    .append(javaString(step.resultVariable))
                    .append(", invocationResult);\n")
            }
        }
    }

    private fun renderPropertyAssertion(step: ScenarioStepModel): String {
        val expected = step.expected?.let(::renderValue) ?: "null"
        return buildString {
            append("        Object actual = EntityValues.getValueEx(requireVariable(")
                .append(javaString(requireNotNull(step.targetVariable)))
                .append("), ")
                .append(javaString(requireNotNull(step.propertyPath)))
                .append(");\n")
            append("        assertScenarioValue(actual, ")
                .append(javaString(requireNotNull(step.operator).name))
                .append(", ")
                .append(expected)
                .append(");\n")
        }
    }

    private fun renderValueAssertion(step: ScenarioStepModel): String {
        val expected = step.expected?.let(::renderValue) ?: "null"
        return buildString {
            append("        assertScenarioValue(requireVariable(")
                .append(javaString(requireNotNull(step.targetVariable)))
                .append("), ")
                .append(javaString(requireNotNull(step.operator).name))
                .append(", ")
                .append(expected)
                .append(");\n")
        }
    }

    private fun renderServiceFailureAssertion(step: ScenarioStepModel): String {
        val args = step.arguments.joinToString(", ") { renderValue(it) }
        val invocation = "invokeBean(${javaString(requireNotNull(step.beanName))}, " +
            "${javaString(requireNotNull(step.methodName))}, new Object[]{$args})"
        return buildString {
            append("        Throwable expectedFailure = null;\n")
            append("        try {\n")
            append("            runAs(")
                .append(javaString(step.actorMode.name))
                .append(", ")
                .append(nullableJavaString(step.username))
                .append(", () -> ")
                .append(invocation)
                .append(");\n")
            append("        } catch (Throwable failure) {\n")
            append("            expectedFailure = rootCause(failure);\n")
            append("        }\n")
            append("        assertThat(expectedFailure).as(\"Expected service invocation to fail\").isNotNull();\n")
            append("        assertThat(loadClass(")
                .append(javaString(requireNotNull(step.expectedExceptionClass)))
                .append(").isInstance(expectedFailure)).isTrue();\n")
            step.messageContains?.takeIf(String::isNotBlank)?.let { message ->
                append("        assertThat(String.valueOf(expectedFailure.getMessage())).contains(")
                    .append(javaString(message))
                    .append(");\n")
            }
        }
    }

    private fun renderEntityCount(step: ScenarioStepModel): String =
        buildString {
            append("        Object countResult = runAs(")
                .append(javaString(step.actorMode.name))
                .append(", ")
                .append(nullableJavaString(step.username))
                .append(", () -> Long.valueOf(dataManager.load((Class) loadClass(")
                .append(javaString(requireNotNull(step.entityClass)))
                .append(")).query(")
                .append(javaString(requireNotNull(step.jpql)))
                .append(").list().size()));\n")
            append("        assertThat(((Number) countResult).longValue()).isEqualTo(")
                .append(requireNotNull(step.expectedCount))
                .append("L);\n")
        }

    private fun renderValue(value: ScenarioValueModel): String =
        when (value.type) {
            ScenarioValueType.STRING -> javaString(value.value.orEmpty())
            ScenarioValueType.INTEGER -> "Integer.valueOf(${javaString(value.value.orEmpty())})"
            ScenarioValueType.LONG -> "Long.valueOf(${javaString(value.value.orEmpty())})"
            ScenarioValueType.DECIMAL -> "new BigDecimal(${javaString(value.value.orEmpty())})"
            ScenarioValueType.BOOLEAN -> "Boolean.valueOf(${javaString(value.value.orEmpty())})"
            ScenarioValueType.UUID -> "UUID.fromString(${javaString(value.value.orEmpty())})"
            ScenarioValueType.LOCAL_DATE -> "LocalDate.parse(${javaString(value.value.orEmpty())})"
            ScenarioValueType.LOCAL_DATETIME -> "LocalDateTime.parse(${javaString(value.value.orEmpty())})"
            ScenarioValueType.OFFSET_DATETIME -> "OffsetDateTime.parse(${javaString(value.value.orEmpty())})"
            ScenarioValueType.INSTANT -> "Instant.parse(${javaString(value.value.orEmpty())})"
            ScenarioValueType.ENUM ->
                "Enum.valueOf((Class) loadClass(${javaString(value.javaType.orEmpty())}), ${javaString(value.value.orEmpty())})"
            ScenarioValueType.NULL -> "null"
            ScenarioValueType.VARIABLE -> "requireVariable(${javaString(value.value.orEmpty())})"
        }

    private fun javaString(value: String): String =
        buildString {
            append('"')
            value.forEach { character ->
                when (character) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> if (character.code < 32) {
                        append("\\u").append(character.code.toString(16).padStart(4, '0'))
                    } else {
                        append(character)
                    }
                }
            }
            append('"')
        }

    private fun nullableJavaString(value: String?): String =
        value?.takeIf(String::isNotBlank)?.let(::javaString) ?: "null"

    private fun safeComment(value: String): String =
        value.replace("*/", "* /").replace(Regex("""\s+"""), " ").trim()

    private val CLEANUP_AND_HELPERS = """
    @AfterEach
    void cleanUpScenarioData() {
        systemAuthenticator.runWithSystem(() -> {
            RuntimeException cleanupFailure = null;
            for (int index = createdEntities.size() - 1; index >= 0; index--) {
                try {
                    dataManager.remove(createdEntities.get(index));
                } catch (RuntimeException failure) {
                    if (cleanupFailure == null) {
                        cleanupFailure = failure;
                    }
                }
            }
            createdEntities.clear();
            variables.clear();
            if (cleanupFailure != null) {
                throw cleanupFailure;
            }
        });
    }

    private Object requireVariable(String name) {
        if (!variables.containsKey(name)) {
            throw new IllegalStateException("Scenario variable is not available: " + name);
        }
        return variables.get(name);
    }

    private Throwable rootCause(Throwable failure) {
        Throwable current = failure;
        while (current.getCause() != null && current.getCause() != current) {
            current = current.getCause();
        }
        return current;
    }

    private Class<?> loadClass(String qualifiedName) {
        try {
            return Class.forName(qualifiedName);
        } catch (ClassNotFoundException failure) {
            throw new IllegalStateException("Scenario class is not available: " + qualifiedName, failure);
        }
    }

    private Object invokeBean(String beanName, String methodName, Object[] arguments) throws Exception {
        Object bean = applicationContext.getBean(beanName);
        List<Method> compatible = new ArrayList<>();
        for (Method method : bean.getClass().getMethods()) {
            if (!method.isBridge()
                    && method.getName().equals(methodName)
                    && method.getParameterCount() == arguments.length
                    && parametersAccept(method.getParameterTypes(), arguments)) {
                compatible.add(method);
            }
        }
        if (compatible.size() != 1) {
            throw new IllegalStateException(
                    "Expected one compatible method for " + beanName + "." + methodName
                            + " but found " + compatible.size());
        }
        try {
            return compatible.get(0).invoke(bean, arguments);
        } catch (InvocationTargetException failure) {
            Throwable target = failure.getTargetException();
            if (target instanceof Exception exception) {
                throw exception;
            }
            if (target instanceof Error error) {
                throw error;
            }
            throw new IllegalStateException(target);
        }
    }

    private boolean parametersAccept(Class<?>[] parameterTypes, Object[] arguments) {
        for (int index = 0; index < parameterTypes.length; index++) {
            Object argument = arguments[index];
            Class<?> parameterType = wrapPrimitive(parameterTypes[index]);
            if (argument == null) {
                if (parameterTypes[index].isPrimitive()) {
                    return false;
                }
            } else if (!parameterType.isInstance(argument)) {
                return false;
            }
        }
        return true;
    }

    private Class<?> wrapPrimitive(Class<?> type) {
        if (!type.isPrimitive()) return type;
        if (type == boolean.class) return Boolean.class;
        if (type == byte.class) return Byte.class;
        if (type == short.class) return Short.class;
        if (type == int.class) return Integer.class;
        if (type == long.class) return Long.class;
        if (type == float.class) return Float.class;
        if (type == double.class) return Double.class;
        if (type == char.class) return Character.class;
        return type;
    }

    private <T> T runAs(String mode, String username, ScenarioOperation<T> operation) {
        if ("USER".equals(mode)) {
            if (username == null || username.isBlank()) {
                throw new IllegalStateException("A username is required for a user-scoped scenario step.");
            }
            return systemAuthenticator.withUser(username, () -> execute(operation));
        }
        return systemAuthenticator.withSystem(() -> execute(operation));
    }

    private <T> T execute(ScenarioOperation<T> operation) {
        try {
            return operation.run();
        } catch (RuntimeException failure) {
            throw failure;
        } catch (Exception failure) {
            throw new IllegalStateException("Scenario step failed", failure);
        }
    }

    private void assertScenarioValue(Object actual, String operator, Object expected) {
        switch (operator) {
            case "EQUALS" -> assertThat(actual).isEqualTo(expected);
            case "NOT_EQUALS" -> assertThat(actual).isNotEqualTo(expected);
            case "NULL" -> assertThat(actual).isNull();
            case "NOT_NULL" -> assertThat(actual).isNotNull();
            case "TRUE" -> assertThat(actual).isEqualTo(Boolean.TRUE);
            case "FALSE" -> assertThat(actual).isEqualTo(Boolean.FALSE);
            case "GREATER_THAN" -> assertThat(compare(actual, expected)).isGreaterThan(0);
            case "LESS_THAN" -> assertThat(compare(actual, expected)).isLessThan(0);
            case "CONTAINS" -> assertContains(actual, expected);
            default -> fail("Unsupported scenario assertion operator: " + operator);
        }
    }

    private int compare(Object actual, Object expected) {
        if (!(actual instanceof Comparable comparable)) {
            throw new AssertionError("Actual value is not comparable: " + actual);
        }
        try {
            return comparable.compareTo(expected);
        } catch (ClassCastException failure) {
            throw new AssertionError("Scenario values cannot be compared: " + actual + " and " + expected, failure);
        }
    }

    private void assertContains(Object actual, Object expected) {
        if (actual instanceof String text) {
            assertThat(text).contains(String.valueOf(expected));
            return;
        }
        if (actual instanceof Collection<?> collection) {
            assertThat(collection).contains(expected);
            return;
        }
        throw new AssertionError("CONTAINS requires a String or Collection actual value.");
    }

    @FunctionalInterface
    private interface ScenarioOperation<T> {
        T run() throws Exception;
    }

""".trimIndent().prependIndent("    ")
}
