import type {
  ApplicationGraphResponse,
  ProjectConfig,
  SecurityWorkspaceSnapshot,
} from '../types'

const locator = (relativePath: string) => ({
  relativePath,
  revisionFingerprint: 'development-preview',
})

export const developmentProjectConfig: ProjectConfig = {
  projectRoot: '/development/payroll-platform',
  basePackage: 'com.company.payroll',
  sourceRoot: 'src/main/java',
  resourceRoot: 'src/main/resources',
  jmixVersion: '2.7',
  databaseType: 'PostgreSQL',
}

export const developmentApplicationGraph: ApplicationGraphResponse = {
  artifacts: [
    {
      id: 'entity-loan',
      kind: 'ENTITY',
      semanticKey: 'com.company.loan.entity.LoanApp',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-entity-loan',
      displayName: 'LoanApp',
      summary: 'Aggregate root for employee loan applications and their approval lifecycle.',
      diagnostics: [],
    },
    {
      id: 'view-loans',
      kind: 'VIEW_DESCRIPTOR',
      semanticKey: 'payroll_LoanApp.list',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/resources/com/company/loan/loan-app-list-view.xml'),
      origin: 'XML_SOURCE',
      fingerprint: 'development-view-loans',
      displayName: 'Loan applications',
      summary: 'FlowUI list view bound to LoanApp with filters, actions, and role-sensitive data.',
      diagnostics: [],
    },
    {
      id: 'menu-loans',
      kind: 'MENU_ITEM',
      semanticKey: 'menu.xml#loanApplications',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
      origin: 'XML_SOURCE',
      fingerprint: 'development-menu-loans',
      displayName: 'Loan applications menu',
      summary: 'Main navigation entry opening the loan application list.',
      diagnostics: [],
    },
    {
      id: 'service-loan',
      kind: 'SERVICE',
      semanticKey: 'com.company.loan.service.LoanApplicationService',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/java/com/company/loan/service/LoanApplicationService.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-service-loan',
      displayName: 'LoanApplicationService',
      summary: 'Transactional loan approval, disbursement, settlement, and closure operations.',
      diagnostics: [],
    },
    {
      id: 'role-payroll',
      kind: 'RESOURCE_ROLE',
      semanticKey: 'com.company.payroll.security.PayrollOfficerRole',
      owner: { buildId: 'payroll-platform', moduleId: 'payroll', sourceSetId: 'main' },
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-role-payroll',
      displayName: 'Payroll officer',
      summary: 'UI and API resource grants inherited by payroll operators.',
      diagnostics: [],
    },
    {
      id: 'role-own-loans',
      kind: 'ROW_ROLE',
      semanticKey: 'com.company.loan.security.OwnLoansRole',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-role-own-loans',
      displayName: 'Own loan applications only',
      summary: 'Row-level restriction limiting LoanApp reads to the authenticated employee.',
      diagnostics: [],
    },
  ],
  relationships: [
    {
      sourceArtifactId: 'view-loans',
      targetArtifactId: 'entity-loan',
      type: 'BINDS_TO',
      sourceLocator: locator('loan/src/main/resources/com/company/loan/loan-app-list-view.xml'),
    },
    {
      sourceArtifactId: 'menu-loans',
      targetArtifactId: 'view-loans',
      type: 'OPENS',
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      sourceArtifactId: 'service-loan',
      targetArtifactId: 'entity-loan',
      type: 'USES',
      sourceLocator: locator('loan/src/main/java/com/company/loan/service/LoanApplicationService.java'),
    },
    {
      sourceArtifactId: 'role-payroll',
      targetArtifactId: 'view-loans',
      type: 'GRANTS_ACCESS_TO',
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      sourceArtifactId: 'role-own-loans',
      targetArtifactId: 'entity-loan',
      type: 'APPLIES_POLICY_TO',
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  diagnostics: [],
  summary: {
    artifactCount: 6,
    relationshipCount: 5,
    diagnosticCount: 0,
    unresolvedRelationshipCount: 0,
    countsByKind: {
      ENTITY: 1,
      VIEW_DESCRIPTOR: 1,
      MENU_ITEM: 1,
      SERVICE: 1,
      RESOURCE_ROLE: 1,
      ROW_ROLE: 1,
    },
  },
  scannedFiles: 6,
  candidateFiles: 6,
  excludedFiles: 0,
  excludedBytes: 0,
  reusedFiles: 0,
  changedFiles: 6,
  cacheHit: true,
  durationMillis: 1,
  snapshotDigest: 'development-application-preview',
}

export const developmentSecurityWorkspace: SecurityWorkspaceSnapshot = {
  graphDigest: 'development-security-preview',
  roles: [
    {
      id: 'role-employee',
      className: 'com.company.payroll.security.EmployeeRole',
      name: 'Employee self service',
      code: 'employee-self-service',
      kind: 'RESOURCE',
      scopes: ['UI'],
      moduleId: 'employee',
      policyIds: ['policy-employee-menu', 'policy-employee-view', 'policy-employee-entity'],
      inheritedRoleIds: [],
      unresolvedBaseRoleCount: 0,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'role-payroll',
      className: 'com.company.payroll.security.PayrollOfficerRole',
      name: 'Payroll officer',
      code: 'payroll-officer',
      kind: 'RESOURCE',
      scopes: ['UI', 'API'],
      moduleId: 'payroll',
      policyIds: ['policy-payroll-menu', 'policy-payroll-entity'],
      inheritedRoleIds: ['role-employee'],
      unresolvedBaseRoleCount: 0,
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      id: 'role-own-loans',
      className: 'com.company.loan.security.OwnLoansRole',
      name: 'Own loan applications only',
      code: 'own-loans',
      kind: 'ROW_LEVEL',
      scopes: ['ALL'],
      moduleId: 'loan',
      policyIds: ['policy-own-loans'],
      inheritedRoleIds: [],
      unresolvedBaseRoleCount: 0,
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  policies: [
    {
      id: 'policy-employee-menu',
      roleId: 'role-employee',
      type: 'MenuPolicy',
      effect: 'GRANT',
      actions: [],
      resourceExpressions: ['loanApplications'],
      targetArtifactIds: ['menu-loans'],
      wildcard: false,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'policy-employee-view',
      roleId: 'role-employee',
      type: 'ViewPolicy',
      effect: 'GRANT',
      actions: [],
      resourceExpressions: ['payroll_LoanApp.list'],
      targetArtifactIds: ['view-loans'],
      wildcard: false,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'policy-employee-entity',
      roleId: 'role-employee',
      type: 'EntityPolicy',
      effect: 'GRANT',
      actions: ['READ', 'CREATE', 'UPDATE'],
      resourceExpressions: ['com.company.loan.entity.LoanApp'],
      targetArtifactIds: ['entity-loan'],
      wildcard: false,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'policy-payroll-menu',
      roleId: 'role-payroll',
      type: 'MenuPolicy',
      effect: 'GRANT',
      actions: [],
      resourceExpressions: ['payrollRuns'],
      targetArtifactIds: ['menu-payroll'],
      wildcard: false,
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      id: 'policy-payroll-entity',
      roleId: 'role-payroll',
      type: 'EntityPolicy',
      effect: 'GRANT',
      actions: ['ALL'],
      resourceExpressions: ['com.company.payroll.entity.PayrollRun'],
      targetArtifactIds: ['entity-payroll'],
      wildcard: false,
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      id: 'policy-own-loans',
      roleId: 'role-own-loans',
      type: 'JpqlRowLevelPolicy',
      effect: 'RESTRICT',
      actions: [],
      resourceExpressions: ['com.company.loan.entity.LoanApp'],
      targetArtifactIds: ['entity-loan'],
      wildcard: false,
      condition: 'where {E}.employee.user.id = :current_user_id',
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  surfaces: [
    {
      artifactId: 'menu-loans',
      kind: 'MENU',
      displayName: 'loanApplications',
      semanticKey: 'menu.xml#loanApplications',
      moduleId: 'loan',
      grantingRoleIds: ['role-employee', 'role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      artifactId: 'menu-payroll',
      kind: 'MENU',
      displayName: 'payrollRuns',
      semanticKey: 'menu.xml#payrollRuns',
      moduleId: 'payroll',
      grantingRoleIds: ['role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
    {
      artifactId: 'view-loans',
      kind: 'VIEW',
      displayName: 'payroll_LoanApp.list',
      semanticKey: 'payroll_LoanApp.list',
      moduleId: 'loan',
      grantingRoleIds: ['role-employee', 'role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('loan/src/main/resources/com/company/loan/loan-app-list-view.xml'),
    },
    {
      artifactId: 'view-payroll',
      kind: 'VIEW',
      displayName: 'payroll_PayrollRun.list',
      semanticKey: 'payroll_PayrollRun.list',
      moduleId: 'payroll',
      grantingRoleIds: [],
      restrictingRoleIds: [],
      sourceLocator: locator('payroll/src/main/resources/com/company/payroll/payroll-run-list-view.xml'),
    },
    {
      artifactId: 'entity-loan',
      kind: 'ENTITY',
      displayName: 'LoanApp',
      semanticKey: 'com.company.loan.entity.LoanApp',
      moduleId: 'loan',
      grantingRoleIds: ['role-employee', 'role-payroll'],
      restrictingRoleIds: ['role-own-loans'],
      sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
    },
    {
      artifactId: 'entity-payroll',
      kind: 'ENTITY',
      displayName: 'PayrollRun',
      semanticKey: 'com.company.payroll.entity.PayrollRun',
      moduleId: 'payroll',
      grantingRoleIds: ['role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/entity/PayrollRun.java'),
    },
  ],
  menuRoutes: [
    {
      menuArtifactId: 'menu-loans',
      viewArtifactId: 'view-loans',
      menuId: 'loanApplications',
      viewId: 'payroll_LoanApp.list',
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      menuArtifactId: 'menu-payroll',
      viewArtifactId: 'view-payroll',
      menuId: 'payrollRuns',
      viewId: 'payroll_PayrollRun.list',
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
  ],
  findings: [
    {
      code: 'JVW-SECURITY-MENU-VIEW-MISMATCH',
      severity: 'ERROR',
      title: 'Menu grants a view the role cannot open',
      message: 'Payroll officer can see payrollRuns, but has no indexed ViewPolicy for payroll_PayrollRun.list.',
      remediation: 'Grant the connected view to the same role or remove the menu grant.',
      roleId: 'role-payroll',
      artifactId: 'menu-payroll',
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
    {
      code: 'P2_ROW_POLICY_NESTED_GRAPH_COVERAGE',
      severity: 'WARNING',
      title: 'Row policy nested graph coverage',
      message: 'LoanApp has JPQL row filtering but no predicate policy for nested object graphs.',
      remediation: 'Add a matching READ predicate if LoanApp can be loaded inside another entity graph.',
      roleId: 'role-own-loans',
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  summary: {
    resourceRoleCount: 2,
    rowRoleCount: 1,
    policyCount: 6,
    coveredSurfaceCount: 5,
    uncoveredMenuCount: 0,
    uncoveredViewCount: 1,
    errorCount: 1,
    warningCount: 1,
  },
}
