import type {
  ApplicationGraphResponse,
  FlowUiAttributeSnapshot,
  FlowUiElementSnapshot,
  FlowUiWorkspaceResponse,
  IntegrationConnectorWorkspaceResponse,
  JmixEnvironmentWorkspace,
  JmixProjectPropertiesWorkspace,
  ProjectConfig,
  RestApiWorkspaceResponse,
  ScenarioWorkspaceResponse,
  SchemaWorkspaceResponse,
  SecurityWorkspaceSnapshot,
  DmnDecisionWorkspaceResponse,
  VisualLogicWorkspaceResponse,
  VisualRuleWorkspaceResponse,
} from '../types'

const locator = (relativePath: string) => ({
  relativePath,
  revisionFingerprint: 'development-preview',
})

export const developmentProjectConfig: ProjectConfig = {
  projectRoot: '/development/payroll-platform',
  basePackage: 'com.company.payroll',
  sourceRoot: 'src/main/java',
  resourceRoot: 'src/main/resources',
  jmixVersion: '2.7',
  projectId: 'payroll',
  databaseType: 'PostgreSQL',
}

export const developmentProjectPropertiesWorkspace: JmixProjectPropertiesWorkspace = {
  jmixVersion: '2.8.2',
  jmixVersionConfidence: 'STRONG',
  observedJmixVersions: ['2.8.2'],
  targetJava: 21,
  targetJavaConfidence: 'STRONG',
  observedTargetJavaVersions: [21],
  addOns: [
    {
      coordinate: 'io.jmix.flowui:jmix-flowui-starter:2.8.2',
      kind: 'PUBLIC',
      sourceKind: 'STATIC_BUILD_FILE',
      sourceId: 'build.gradle',
    },
  ],
  buildFiles: [locator('build.gradle'), locator('loan/build.gradle')],
  settingsFiles: [locator('settings.gradle')],
  profiles: [
    {
      modulePath: '',
      profile: 'default',
      locator: locator('src/main/resources/application.properties'),
      serverPort: '8080',
      contextPath: '/payroll',
      activeProfiles: ['dev'],
      availableLocales: ['en', 'bn'],
      stores: [
        {
          name: 'main',
          declaredAdditional: true,
          url: 'jdbc:postgresql://localhost/payroll',
          username: 'payroll',
          passwordConfigured: true,
          passwordUsesPlaceholder: true,
          liquibaseChangeLog: 'com/company/payroll/liquibase/changelog.xml',
        },
      ],
      properties: [
        {
          key: 'spring.profiles.active',
          displayValue: 'dev',
          secret: false,
        },
        {
          key: 'main.datasource.password',
          displayValue: '${DB_PASSWORD:••••••••}',
          secret: true,
        },
      ],
    },
    {
      modulePath: '',
      profile: 'dev',
      locator: locator('src/main/resources/application-dev.properties'),
      serverPort: '8081',
      contextPath: '/payroll',
      activeProfiles: [],
      availableLocales: ['en', 'bn'],
      stores: [
        {
          name: 'main',
          declaredAdditional: true,
          url: 'jdbc:postgresql://localhost/payroll_dev',
          username: 'payroll',
          passwordConfigured: true,
          passwordUsesPlaceholder: true,
          liquibaseChangeLog: 'com/company/payroll/liquibase/changelog.xml',
        },
      ],
      properties: [
        {
          key: 'server.port',
          displayValue: '8081',
          secret: false,
        },
        {
          key: 'main.datasource.url',
          displayValue: 'jdbc:postgresql://localhost/payroll_dev',
          secret: false,
        },
        {
          key: 'main.datasource.password',
          displayValue: '${DB_PASSWORD}',
          secret: true,
        },
      ],
    },
  ],
  issues: [],
  snapshotDigest: 'development-project-properties',
}

export const developmentEnvironmentWorkspace: JmixEnvironmentWorkspace = {
  files: [
    {
      relativePath: '.env',
      locator: locator('.env'),
      existing: true,
      mutable: true,
      importedBy: [
        {
          profileLocator: locator('src/main/resources/application.properties'),
          profile: 'default',
          modulePath: '',
          optional: true,
          declaration: 'optional:file:.env[.properties]',
        },
      ],
      variables: [
        {
          name: 'SPRING_PROFILES_ACTIVE',
          displayValue: 'dev',
          secret: false,
          mutable: true,
          references: [
            {
              profileLocator: locator('src/main/resources/application.properties'),
              propertyKey: 'spring.profiles.active',
              secretProperty: false,
            },
          ],
        },
        {
          name: 'DB_PASSWORD',
          displayValue: '••••••••',
          secret: true,
          mutable: true,
          references: [
            {
              profileLocator: locator('src/main/resources/application.properties'),
              propertyKey: 'main.datasource.password',
              secretProperty: true,
            },
          ],
        },
      ],
    },
  ],
  connectionCandidates: [
    {
      profileLocator: locator('src/main/resources/application-dev.properties'),
      profile: 'dev',
      modulePath: '',
      proposedRelativePath: '.env',
    },
  ],
  activations: [
    {
      modulePath: '',
      declarationLocator: locator('src/main/resources/application.properties'),
      rawExpression: '${SPRING_PROFILES_ACTIVE:dev}',
      source: 'IMPORTED_ENV',
      declaredProfiles: ['dev'],
      expandedProfiles: ['dev'],
      missingProfiles: [],
      runtimeProven: false,
      explanation:
        'Resolved from an explicitly imported environment file; launch/runtime use is not yet proven.',
    },
  ],
  launchConfigurations: [
    {
      relativePath: '.run/Payroll.run.xml',
      revisionFingerprint: 'development-preview',
      activeProfiles: ['dev'],
      environmentFiles: ['.env'],
      runtimeProven: false,
      explanation:
        'This is launch-configuration evidence. Start and inspect the process before calling it runtime active.',
    },
  ],
  issues: [],
  snapshotDigest: 'development-environment-workspace',
}

export const developmentApplicationGraph: ApplicationGraphResponse = {
  artifacts: [
    {
      id: 'entity-loan',
      kind: 'ENTITY',
      semanticKey: 'com.company.loan.entity.LoanApp',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-entity-loan',
      displayName: 'LoanApp',
      summary: 'Aggregate root for employee loan applications and their approval lifecycle.',
      diagnostics: [],
    },
    {
      id: 'view-loans',
      kind: 'VIEW_DESCRIPTOR',
      semanticKey: 'payroll_LoanApp.list',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/resources/com/company/loan/loan-app-list-view.xml'),
      origin: 'XML_SOURCE',
      fingerprint: 'development-view-loans',
      displayName: 'Loan applications',
      summary: 'FlowUI list view bound to LoanApp with filters, actions, and role-sensitive data.',
      diagnostics: [],
    },
    {
      id: 'menu-loans',
      kind: 'MENU_ITEM',
      semanticKey: 'menu.xml#loanApplications',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
      origin: 'XML_SOURCE',
      fingerprint: 'development-menu-loans',
      displayName: 'Loan applications menu',
      summary: 'Main navigation entry opening the loan application list.',
      diagnostics: [],
    },
    {
      id: 'service-loan',
      kind: 'SERVICE',
      semanticKey: 'com.company.loan.service.LoanApplicationService',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/java/com/company/loan/service/LoanApplicationService.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-service-loan',
      displayName: 'LoanApplicationService',
      summary: 'Transactional loan approval, disbursement, settlement, and closure operations.',
      diagnostics: [],
    },
    {
      id: 'role-payroll',
      kind: 'RESOURCE_ROLE',
      semanticKey: 'com.company.payroll.security.PayrollOfficerRole',
      owner: { buildId: 'payroll-platform', moduleId: 'payroll', sourceSetId: 'main' },
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-role-payroll',
      displayName: 'Payroll officer',
      summary: 'UI and API resource grants inherited by payroll operators.',
      diagnostics: [],
    },
    {
      id: 'role-own-loans',
      kind: 'ROW_ROLE',
      semanticKey: 'com.company.loan.security.OwnLoansRole',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
      origin: 'JAVA_SOURCE',
      fingerprint: 'development-role-own-loans',
      displayName: 'Own loan applications only',
      summary: 'Row-level restriction limiting LoanApp reads to the authenticated employee.',
      diagnostics: [],
    },
    {
      id: 'decision-loan-eligibility',
      kind: 'DECISION_TABLE',
      semanticKey: 'loanEligibility',
      owner: { buildId: 'payroll-platform', moduleId: 'loan', sourceSetId: 'main' },
      sourceLocator: locator('loan/src/main/resources/dmn/loan-eligibility.dmn'),
      origin: 'RESOURCE',
      fingerprint: 'development-decision-loan-eligibility',
      displayName: 'Loan eligibility',
      summary: 'DMN decision table · UNIQUE',
      diagnostics: [],
    },
  ],
  relationships: [
    {
      sourceArtifactId: 'view-loans',
      targetArtifactId: 'entity-loan',
      type: 'BINDS_TO',
      sourceLocator: locator('loan/src/main/resources/com/company/loan/loan-app-list-view.xml'),
    },
    {
      sourceArtifactId: 'menu-loans',
      targetArtifactId: 'view-loans',
      type: 'OPENS',
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      sourceArtifactId: 'service-loan',
      targetArtifactId: 'entity-loan',
      type: 'USES',
      sourceLocator: locator('loan/src/main/java/com/company/loan/service/LoanApplicationService.java'),
    },
    {
      sourceArtifactId: 'role-payroll',
      targetArtifactId: 'view-loans',
      type: 'GRANTS_ACCESS_TO',
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      sourceArtifactId: 'role-own-loans',
      targetArtifactId: 'entity-loan',
      type: 'APPLIES_POLICY_TO',
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  diagnostics: [],
  summary: {
    artifactCount: 7,
    relationshipCount: 5,
    diagnosticCount: 0,
    unresolvedRelationshipCount: 0,
    countsByKind: {
      ENTITY: 1,
      VIEW_DESCRIPTOR: 1,
      MENU_ITEM: 1,
      SERVICE: 1,
      RESOURCE_ROLE: 1,
      ROW_ROLE: 1,
      DECISION_TABLE: 1,
    },
  },
  scannedFiles: 7,
  candidateFiles: 7,
  excludedFiles: 0,
  excludedBytes: 0,
  unreadableFiles: 0,
  parseErrorFiles: 0,
  parserUnavailableFiles: 0,
  reusedFiles: 0,
  changedFiles: 7,
  cacheHit: true,
  durationMillis: 1,
  modules: [
    {
      moduleId: 'loan',
      buildIds: ['payroll-platform'],
      contentRootCount: 1,
      sourceRootCount: 2,
      fallbackContentRootCount: 0,
      discoveredSourceRootCount: 0,
      candidateFileCount: 5,
      indexedFileCount: 5,
      sourceSets: ['main'],
      moduleRoot: 'loan',
      sourceRoots: [
        {
          moduleId: 'loan',
          relativePath: 'loan/src/main/java',
          sourceSetId: 'main',
          buildId: 'payroll-platform',
          kind: 'JAVA',
          recovered: false,
        },
        {
          moduleId: 'loan',
          relativePath: 'loan/src/main/resources',
          sourceSetId: 'main',
          buildId: 'payroll-platform',
          kind: 'RESOURCES',
          recovered: false,
        },
      ],
    },
    {
      moduleId: 'payroll',
      buildIds: ['payroll-platform'],
      contentRootCount: 1,
      sourceRootCount: 2,
      fallbackContentRootCount: 0,
      discoveredSourceRootCount: 0,
      candidateFileCount: 2,
      indexedFileCount: 2,
      sourceSets: ['main'],
      moduleRoot: 'payroll',
      sourceRoots: [
        {
          moduleId: 'payroll',
          relativePath: 'payroll/src/main/java',
          sourceSetId: 'main',
          buildId: 'payroll-platform',
          kind: 'JAVA',
          recovered: false,
        },
        {
          moduleId: 'payroll',
          relativePath: 'payroll/src/main/resources',
          sourceSetId: 'main',
          buildId: 'payroll-platform',
          kind: 'RESOURCES',
          recovered: false,
        },
      ],
    },
  ],
  indexHealth: {
    complete: true,
    moduleCount: 2,
    contentRootCount: 2,
    sourceRootCount: 4,
    fallbackContentRootCount: 0,
    unreadableFileCount: 0,
    parseErrorFileCount: 0,
    parserUnavailableFileCount: 0,
    discoveredSourceRootCount: 0,
    recoveredModuleCount: 0,
    overlappingOwnershipFileCount: 0,
    ambiguousOwnershipFileCount: 0,
    unresolvedModuleDependencyCount: 0,
    limitReached: false,
  },
  snapshotDigest: 'development-application-preview',
}

export const developmentScenarioWorkspace: ScenarioWorkspaceResponse = {
  graphDigest: 'development-scenarios',
  destinations: [
    {
      id: 'loan:src/test/java',
      moduleId: 'loan',
      testSourceRoot: 'loan/src/test/java',
      defaultPackage: 'com.company.loan',
      recommended: true,
    },
    {
      id: 'payroll:src/test/java',
      moduleId: 'payroll',
      testSourceRoot: 'payroll/src/test/java',
      defaultPackage: 'com.company.payroll',
      recommended: false,
    },
  ],
  defaultDestinationId: 'loan:src/test/java',
  contextArtifacts: developmentApplicationGraph.artifacts.filter((artifact) =>
    ['ENTITY', 'SERVICE', 'RESOURCE_ROLE', 'ROW_ROLE'].includes(artifact.kind),
  ),
  existingScenarios: [],
  issues: [],
}

export const developmentVisualLogicWorkspace: VisualLogicWorkspaceResponse = {
  graphDigest: 'development-visual-logic',
  destinations: [
    {
      id: 'loan:src/main/java',
      moduleId: 'loan',
      sourceRoot: 'loan/src/main/java',
      defaultPackage: 'com.company.loan.service',
      recommended: true,
    },
    {
      id: 'payroll:src/main/java',
      moduleId: 'payroll',
      sourceRoot: 'payroll/src/main/java',
      defaultPackage: 'com.company.payroll.service',
      recommended: false,
    },
  ],
  defaultDestinationId: 'loan:src/main/java',
  contextArtifacts: developmentApplicationGraph.artifacts.filter((artifact) =>
    ['ENTITY', 'SERVICE', 'RESOURCE_ROLE', 'ROW_ROLE'].includes(artifact.kind),
  ),
  existingDocuments: [],
  issues: [],
}

export const developmentIntegrationConnectorWorkspace: IntegrationConnectorWorkspaceResponse = {
  graphDigest: 'development-integration-connectors',
  destinations: [
    {
      id: 'loan:integration',
      moduleId: 'loan',
      sourceRoot: 'loan/src/main/java',
      resourceRoot: 'loan/src/main/resources',
      defaultPackage: 'com.company.loan.integration',
      capabilities: [
        'SPRING_WEB',
        'SPRING_KAFKA',
        'SPRING_AMQP',
        'SPRING_INTEGRATION_SFTP',
        'RESILIENCE4J',
        'JMIX_EMAIL',
        'JMIX_FILE_STORAGE',
        'OAUTH2_CLIENT',
      ],
      recommended: true,
    },
    {
      id: 'payroll:integration',
      moduleId: 'payroll',
      sourceRoot: 'payroll/src/main/java',
      resourceRoot: 'payroll/src/main/resources',
      defaultPackage: 'com.company.payroll.integration',
      capabilities: ['SPRING_WEB', 'JMIX_FILE_STORAGE'],
      recommended: false,
    },
  ],
  defaultDestinationId: 'loan:integration',
  contextArtifacts: developmentApplicationGraph.artifacts.filter((artifact) =>
    ['SERVICE', 'BUSINESS_RULE', 'REPOSITORY', 'VALIDATOR', 'SOURCE_TYPE'].includes(artifact.kind),
  ),
  oauth2Managers: [{
    beanName: 'authorizedClientManager',
    declaringType: 'com.company.loan.security.OAuth2ClientConfiguration',
    moduleId: 'loan',
    sourceLocator: locator('loan/src/main/java/com/company/loan/security/OAuth2ClientConfiguration.java'),
  }],
  existingDocuments: [],
  issues: [],
}

export const developmentVisualRuleWorkspace: VisualRuleWorkspaceResponse = {
  graphDigest: 'development-visual-rules',
  destinations: developmentVisualLogicWorkspace.destinations,
  defaultDestinationId: developmentVisualLogicWorkspace.defaultDestinationId,
  contextArtifacts: developmentApplicationGraph.artifacts.filter((artifact) =>
    ['ENTITY', 'ENTITY_ATTRIBUTE', 'DTO', 'ENUM', 'BUSINESS_RULE', 'SERVICE', 'VALIDATOR'].includes(artifact.kind),
  ),
  existingDocuments: [],
  issues: [],
}

export const developmentDmnDecisionWorkspace: DmnDecisionWorkspaceResponse = {
  graphDigest: 'development-dmn-decisions',
  destinations: [
    {
      id: 'loan:resources',
      moduleId: 'loan',
      resourceRoot: 'loan/src/main/resources',
      dmnDirectory: 'loan/src/main/resources/dmn',
      recommended: true,
    },
    {
      id: 'payroll:resources',
      moduleId: 'payroll',
      resourceRoot: 'payroll/src/main/resources',
      dmnDirectory: 'payroll/src/main/resources/dmn',
      recommended: false,
    },
  ],
  defaultDestinationId: 'loan:resources',
  existingDocuments: [],
  workflowReferences: [
    {
      processId: 'loanApproval',
      nodeId: 'evaluateEligibility',
      nodeName: 'Evaluate eligibility',
      decisionKey: 'loanEligibility',
      locator: locator('loan/src/main/resources/processes/loan-approval.bpmn20.xml'),
      resolved: false,
    },
  ],
  issues: [],
}

export const developmentRestApiWorkspace: RestApiWorkspaceResponse = {
  graphDigest: 'development-rest-api',
  operations: [
    {
      artifactId: 'rest-service-approve',
      kind: 'SERVICE',
      displayName: 'payroll_LoanService.approve',
      methods: ['GET', 'POST'],
      path: '/rest/services/payroll_LoanService/approve',
      moduleId: 'loan',
      parameters: [{
        name: 'loanId',
        javaType: 'java.util.UUID',
        location: 'QUERY_OR_BODY',
        required: true,
        sourceLocator: locator('loan/src/main/resources/rest/rest-services.xml'),
      }],
      entityArtifactIds: ['entity-loan'],
      entityNames: ['LoanApp'],
      implementationArtifactIds: ['service-loan'],
      securedRoleIds: [],
      transactionBoundary: 'IMPLEMENTATION',
      rowSecurity: 'SERVICE_DEPENDENT',
      sourceLocator: locator('loan/src/main/resources/rest/rest-services.xml'),
    },
    {
      artifactId: 'rest-query-approved',
      kind: 'QUERY',
      displayName: 'approvedLoans',
      methods: ['GET', 'POST'],
      path: '/rest/queries/payroll_LoanApp/approvedLoans',
      moduleId: 'loan',
      parameters: [{
        name: 'employeeId',
        javaType: 'java.util.UUID',
        location: 'QUERY_OR_BODY',
        required: true,
        sourceLocator: locator('loan/src/main/resources/rest/rest-queries.xml'),
      }],
      entityArtifactIds: ['entity-loan'],
      entityNames: ['LoanApp'],
      implementationArtifactIds: [],
      securedRoleIds: [],
      transactionBoundary: 'READ_ONLY',
      rowSecurity: 'ENFORCED_READ',
      queryText: 'select e from payroll_LoanApp e where e.processState = :employeeId',
      fetchPlanName: 'loan-with-account',
      sourceLocator: locator('loan/src/main/resources/rest/rest-queries.xml'),
    },
    {
      artifactId: 'rest-controller-disburse',
      kind: 'CONTROLLER',
      displayName: 'POST /api/loans/{id}/disburse',
      methods: ['POST'],
      path: '/api/loans/{id}/disburse',
      moduleId: 'loan',
      parameters: [],
      entityArtifactIds: ['entity-loan'],
      entityNames: ['LoanApp'],
      implementationArtifactIds: [],
      securedRoleIds: ['role-payroll'],
      transactionBoundary: 'IMPLEMENTATION',
      rowSecurity: 'IMPLEMENTATION_DEPENDENT',
      sourceLocator: locator('loan/src/main/java/com/company/loan/api/LoanController.java'),
    },
  ],
  configs: [
    {
      artifactId: 'rest-services-config',
      kind: 'SERVICES',
      moduleId: 'loan',
      registered: true,
      operationCount: 1,
      sourceLocator: locator('loan/src/main/resources/rest/rest-services.xml'),
    },
    {
      artifactId: 'rest-queries-config',
      kind: 'QUERIES',
      moduleId: 'loan',
      registered: true,
      operationCount: 1,
      sourceLocator: locator('loan/src/main/resources/rest/rest-queries.xml'),
    },
  ],
  apiRoles: [{
    id: 'role-rest-api',
    name: 'Payroll REST client',
    code: 'payroll-rest-client',
    scopes: ['API'],
    sourceLocator: locator('loan/src/main/java/com/company/loan/security/PayrollRestRole.java'),
  }],
  security: {
    restProtected: true,
    authenticatedPatterns: '/rest/**,/api/**',
    anonymousPatterns: '',
    restEnabledRoleCount: 1,
  },
  openApi: {
    genericJsonPath: '/rest/docs/openapi.json',
    detailedJsonPath: '/rest/docs/openapiDetailed.json',
    genericYamlPath: '/rest/docs/openapi.yaml',
    detailedYamlPath: '/rest/docs/openapiDetailed.yaml',
  },
  findings: [{
    code: 'JVW-REST-SERVICE-ROW-SECURITY-MANUAL',
    severity: 'WARNING',
    title: 'Service boundary requires explicit row-security review',
    message: 'payroll_LoanService.approve parameters and results are not automatically checked against row-level policies.',
    remediation: 'Use constrained DataManager and explicit authorization inside the transactional service.',
    operationId: 'rest-service-approve',
    sourceLocator: locator('loan/src/main/resources/rest/rest-services.xml'),
  }],
  summary: {
    controllerCount: 1,
    serviceCount: 1,
    queryCount: 1,
    errorCount: 0,
    warningCount: 1,
  },
}

export const developmentSecurityWorkspace: SecurityWorkspaceSnapshot = {
  graphDigest: 'development-security-preview',
  roles: [
    {
      id: 'role-employee',
      className: 'com.company.payroll.security.EmployeeRole',
      name: 'Employee self service',
      code: 'employee-self-service',
      kind: 'RESOURCE',
      scopes: ['UI'],
      moduleId: 'employee',
      policyIds: ['policy-employee-menu', 'policy-employee-view', 'policy-employee-entity'],
      inheritedRoleIds: [],
      unresolvedBaseRoleCount: 0,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'role-payroll',
      className: 'com.company.payroll.security.PayrollOfficerRole',
      name: 'Payroll officer',
      code: 'payroll-officer',
      kind: 'RESOURCE',
      scopes: ['UI', 'API'],
      moduleId: 'payroll',
      policyIds: ['policy-payroll-menu', 'policy-payroll-entity'],
      inheritedRoleIds: ['role-employee'],
      unresolvedBaseRoleCount: 0,
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      id: 'role-own-loans',
      className: 'com.company.loan.security.OwnLoansRole',
      name: 'Own loan applications only',
      code: 'own-loans',
      kind: 'ROW_LEVEL',
      scopes: ['ALL'],
      moduleId: 'loan',
      policyIds: ['policy-own-loans'],
      inheritedRoleIds: [],
      unresolvedBaseRoleCount: 0,
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  policies: [
    {
      id: 'policy-employee-menu',
      roleId: 'role-employee',
      type: 'MenuPolicy',
      effect: 'GRANT',
      actions: [],
      resourceExpressions: ['loanApplications'],
      targetArtifactIds: ['menu-loans'],
      wildcard: false,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'policy-employee-view',
      roleId: 'role-employee',
      type: 'ViewPolicy',
      effect: 'GRANT',
      actions: [],
      resourceExpressions: ['payroll_LoanApp.list'],
      targetArtifactIds: ['view-loans'],
      wildcard: false,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'policy-employee-entity',
      roleId: 'role-employee',
      type: 'EntityPolicy',
      effect: 'GRANT',
      actions: ['READ', 'CREATE', 'UPDATE'],
      resourceExpressions: ['com.company.loan.entity.LoanApp'],
      targetArtifactIds: ['entity-loan'],
      wildcard: false,
      sourceLocator: locator('employee/src/main/java/com/company/payroll/security/EmployeeRole.java'),
    },
    {
      id: 'policy-payroll-menu',
      roleId: 'role-payroll',
      type: 'MenuPolicy',
      effect: 'GRANT',
      actions: [],
      resourceExpressions: ['payrollRuns'],
      targetArtifactIds: ['menu-payroll'],
      wildcard: false,
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      id: 'policy-payroll-entity',
      roleId: 'role-payroll',
      type: 'EntityPolicy',
      effect: 'GRANT',
      actions: ['ALL'],
      resourceExpressions: ['com.company.payroll.entity.PayrollRun'],
      targetArtifactIds: ['entity-payroll'],
      wildcard: false,
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/security/PayrollOfficerRole.java'),
    },
    {
      id: 'policy-own-loans',
      roleId: 'role-own-loans',
      type: 'JpqlRowLevelPolicy',
      effect: 'RESTRICT',
      actions: [],
      resourceExpressions: ['com.company.loan.entity.LoanApp'],
      targetArtifactIds: ['entity-loan'],
      wildcard: false,
      condition: 'where {E}.employee.user.id = :current_user_id',
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  surfaces: [
    {
      artifactId: 'menu-loans',
      kind: 'MENU',
      displayName: 'loanApplications',
      semanticKey: 'menu.xml#loanApplications',
      moduleId: 'loan',
      grantingRoleIds: ['role-employee', 'role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      artifactId: 'menu-payroll',
      kind: 'MENU',
      displayName: 'payrollRuns',
      semanticKey: 'menu.xml#payrollRuns',
      moduleId: 'payroll',
      grantingRoleIds: ['role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
    {
      artifactId: 'view-loans',
      kind: 'VIEW',
      displayName: 'payroll_LoanApp.list',
      semanticKey: 'payroll_LoanApp.list',
      moduleId: 'loan',
      grantingRoleIds: ['role-employee', 'role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('loan/src/main/resources/com/company/loan/loan-app-list-view.xml'),
    },
    {
      artifactId: 'view-payroll',
      kind: 'VIEW',
      displayName: 'payroll_PayrollRun.list',
      semanticKey: 'payroll_PayrollRun.list',
      moduleId: 'payroll',
      grantingRoleIds: [],
      restrictingRoleIds: [],
      sourceLocator: locator('payroll/src/main/resources/com/company/payroll/payroll-run-list-view.xml'),
    },
    {
      artifactId: 'entity-loan',
      kind: 'ENTITY',
      displayName: 'LoanApp',
      semanticKey: 'com.company.loan.entity.LoanApp',
      moduleId: 'loan',
      grantingRoleIds: ['role-employee', 'role-payroll'],
      restrictingRoleIds: ['role-own-loans'],
      sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
    },
    {
      artifactId: 'entity-payroll',
      kind: 'ENTITY',
      displayName: 'PayrollRun',
      semanticKey: 'com.company.payroll.entity.PayrollRun',
      moduleId: 'payroll',
      grantingRoleIds: ['role-payroll'],
      restrictingRoleIds: [],
      sourceLocator: locator('payroll/src/main/java/com/company/payroll/entity/PayrollRun.java'),
    },
  ],
  menuRoutes: [
    {
      menuArtifactId: 'menu-loans',
      viewArtifactId: 'view-loans',
      menuId: 'loanApplications',
      viewId: 'payroll_LoanApp.list',
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      menuArtifactId: 'menu-payroll',
      viewArtifactId: 'view-payroll',
      menuId: 'payrollRuns',
      viewId: 'payroll_PayrollRun.list',
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
  ],
  journeys: [
    {
      menuArtifactId: 'menu-loans',
      menuId: 'loanApplications',
      menuPathArtifactIds: ['menu-loans'],
      menuPathIds: ['loanApplications'],
      viewArtifactId: 'view-loans',
      viewId: 'payroll_LoanApp.list',
      entityArtifactIds: ['entity-loan'],
      attributeArtifactIds: [],
      componentArtifactIds: [],
      unresolvedDependencyCount: 0,
      sourceLocator: locator('loan/src/main/resources/menu.xml'),
    },
    {
      menuArtifactId: 'menu-payroll',
      menuId: 'payrollRuns',
      menuPathArtifactIds: ['menu-payroll'],
      menuPathIds: ['payrollRuns'],
      viewArtifactId: 'view-payroll',
      viewId: 'payroll_PayrollRun.list',
      entityArtifactIds: ['entity-payroll'],
      attributeArtifactIds: [],
      componentArtifactIds: [],
      unresolvedDependencyCount: 0,
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
  ],
  findings: [
    {
      code: 'JVW-SECURITY-MENU-VIEW-MISMATCH',
      severity: 'ERROR',
      title: 'Menu grants a view the role cannot open',
      message: 'Payroll officer can see payrollRuns, but has no indexed ViewPolicy for payroll_PayrollRun.list.',
      remediation: 'Grant the connected view to the same role or remove the menu grant.',
      roleId: 'role-payroll',
      artifactId: 'menu-payroll',
      sourceLocator: locator('payroll/src/main/resources/menu.xml'),
    },
    {
      code: 'P2_ROW_POLICY_NESTED_GRAPH_COVERAGE',
      severity: 'WARNING',
      title: 'Row policy nested graph coverage',
      message: 'LoanApp has JPQL row filtering but no predicate policy for nested object graphs.',
      remediation: 'Add a matching READ predicate if LoanApp can be loaded inside another entity graph.',
      roleId: 'role-own-loans',
      sourceLocator: locator('loan/src/main/java/com/company/loan/security/OwnLoansRole.java'),
    },
  ],
  runtime: {
    sources: [],
    roles: [],
    policies: [],
    assignments: [],
    principals: [],
    issues: [],
    summary: {
      sourceCount: 0,
      roleCount: 0,
      policyCount: 0,
      assignmentCount: 0,
      principalCount: 0,
      errorCount: 0,
      warningCount: 0,
    },
  },
  summary: {
    resourceRoleCount: 2,
    rowRoleCount: 1,
    policyCount: 6,
    coveredSurfaceCount: 5,
    uncoveredMenuCount: 0,
    uncoveredViewCount: 1,
    errorCount: 1,
    warningCount: 1,
  },
}

const flowAttribute = (name: string, value: string): FlowUiAttributeSnapshot => ({
  name,
  value,
  rawValue: value,
  sourceStart: 0,
  sourceEnd: 0,
  valueStart: 0,
  valueEnd: 0,
  quote: '"',
})

const flowElement = (
  key: string,
  localTag: string,
  id: string | undefined,
  parentKey: string | undefined,
  childKeys: string[],
  attributes: Record<string, string> = {},
): FlowUiElementSnapshot => ({
  key,
  tagName: localTag,
  localTag,
  id,
  parentKey,
  childKeys,
  sourceStart: 0,
  startTagEnd: 0,
  endTagStart: childKeys.length ? 1 : 0,
  sourceEnd: 1,
  selfClosing: childKeys.length === 0 && !['layout', 'vbox', 'dataGrid', 'columns', 'actions'].includes(localTag),
  attributes: Object.entries({
    ...(id ? { id } : {}),
    ...attributes,
  }).map(([name, value]) => flowAttribute(name, value)),
  directText: undefined,
  directTextStart: undefined,
  directTextEnd: undefined,
  directTextCdata: false,
})

const developmentFlowElements: FlowUiElementSnapshot[] = [
  flowElement('view', 'view', 'payroll_LoanApp.list', undefined, ['data', 'layout']),
  flowElement('data', 'data', undefined, 'view', ['loanAppsDc', 'selectedLoanDc']),
  flowElement('loanAppsDc', 'collection', 'loanAppsDc', 'data', ['loanAppsDl'], {
    class: 'com.company.loan.entity.LoanApp',
    fetchPlan: '_base',
  }),
  flowElement('loanAppsDl', 'loader', 'loanAppsDl', 'loanAppsDc', ['loanQuery']),
  {
    ...flowElement('loanQuery', 'query', undefined, 'loanAppsDl', []),
    selfClosing: false,
    directText: 'select e from LoanApp e order by e.applicationDate desc',
  },
  flowElement('selectedLoanDc', 'instance', 'selectedLoanDc', 'data', [], {
    class: 'com.company.loan.entity.LoanApp',
    fetchPlan: '_base',
  }),
  flowElement('layout', 'layout', undefined, 'view', ['toolbar', 'loanAppsGrid']),
  flowElement('toolbar', 'hbox', 'toolbar', 'layout', ['loanFilter', 'createButton'], {
    width: '100%',
    wrap: 'true',
  }),
  flowElement('loanFilter', 'genericFilter', 'loanFilter', 'toolbar', [], {
    dataLoader: 'loanAppsDl',
  }),
  flowElement('createButton', 'button', 'createButton', 'toolbar', [], {
    text: 'Create loan',
    action: 'loanAppsGrid.create',
  }),
  flowElement('loanAppsGrid', 'dataGrid', 'loanAppsGrid', 'layout', ['gridColumns', 'gridActions'], {
    dataContainer: 'loanAppsDc',
    width: '100%',
    minHeight: '20em',
  }),
  flowElement('gridColumns', 'columns', undefined, 'loanAppsGrid', ['loanNoColumn', 'amountColumn']),
  flowElement('loanNoColumn', 'column', undefined, 'gridColumns', [], { property: 'applicationNo' }),
  flowElement('amountColumn', 'column', undefined, 'gridColumns', [], { property: 'loanAmount' }),
  flowElement('gridActions', 'actions', undefined, 'loanAppsGrid', ['createAction', 'editAction']),
  flowElement('createAction', 'action', 'create', 'gridActions', [], { type: 'list_create' }),
  flowElement('editAction', 'action', 'edit', 'gridActions', [], { type: 'list_edit' }),
]

export const developmentFlowUiWorkspace: FlowUiWorkspaceResponse = {
  accepted: true,
  document: {
    relativePath: 'loan/src/main/resources/com/company/loan/loan-app-list-view.xml',
    revisionFingerprint: 'development-preview',
    viewId: 'payroll_LoanApp.list',
    rootKey: 'view',
    sourceText: '<view><!-- development visual fixture --></view>',
    elements: developmentFlowElements,
  },
  contextArtifacts: developmentApplicationGraph.artifacts,
  contextRelationships: developmentApplicationGraph.relationships,
  issues: [],
  dataModel: {
    containers: [{
        elementKey: 'loanAppsDc',
        id: 'loanAppsDc',
        kind: 'collection',
        entityClass: 'com.company.loan.entity.LoanApp',
        fetchPlan: '_base',
        loaderElementKey: 'loanAppsDl',
        loaderId: 'loanAppsDl',
        queryElementKey: 'loanQuery',
        query: 'select e from LoanApp e order by e.applicationDate desc',
      }, {
        elementKey: 'selectedLoanDc',
        id: 'selectedLoanDc',
        kind: 'instance',
        entityClass: 'com.company.loan.entity.LoanApp',
        fetchPlan: '_base',
      }],
    bindings: [
      {
        elementKey: 'loanAppsGrid',
        componentId: 'loanAppsGrid',
        componentTag: 'dataGrid',
        containerId: 'loanAppsDc',
      },
    ],
    entityFields: [
      {
        artifactId: 'entity-loan:applicationNo',
        entitySemanticKey: 'com.company.loan.entity.LoanApp',
        name: 'applicationNo',
        type: 'String',
        sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      },
      {
        artifactId: 'entity-loan:loanAmount',
        entitySemanticKey: 'com.company.loan.entity.LoanApp',
        name: 'loanAmount',
        type: 'BigDecimal',
        sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      },
    ],
    queryParameters: [],
  },
  controllerModel: {
    relativePath: 'loan/src/main/java/com/company/loan/view/LoanAppListView.java',
    revisionFingerprint: 'development-controller',
    className: 'LoanAppListView',
    language: 'JAVA',
    psiSupported: true,
    injections: [{
      fieldName: 'loanAppsGrid',
      componentId: 'loanAppsGrid',
      type: 'DataGrid<LoanApp>',
      sourceLocator: locator('loan/src/main/java/com/company/loan/view/LoanAppListView.java'),
    }],
    handlers: [{
      methodName: 'onInit',
      kind: 'Subscribe',
      parameterTypes: ['InitEvent'],
      sourceLocator: locator('loan/src/main/java/com/company/loan/view/LoanAppListView.java'),
    }],
  },
}

export const developmentSchemaWorkspace: SchemaWorkspaceResponse = {
  accepted: true,
  snapshotDigest: 'development-schema',
  modules: [
    { moduleId: 'loan', projectId: 'loan', entityCount: 2, changelogCount: 2, storeCount: 1, findingCount: 2 },
    { moduleId: 'hr', projectId: 'hr', entityCount: 1, changelogCount: 0, storeCount: 0, findingCount: 0 },
    { moduleId: 'payroll', projectId: 'payroll', entityCount: 1, changelogCount: 1, storeCount: 1, findingCount: 0 },
  ],
  stores: [{
    id: 'loan:main',
    name: 'main',
    moduleId: 'loan',
    configuredPath: 'com/company/loan/liquibase/changelog.xml',
    configurationLocator: locator('loan/src/main/resources/application.properties'),
    rootChangelogPath: 'loan/src/main/resources/com/company/loan/liquibase/changelog.xml',
    rootLocator: locator('loan/src/main/resources/com/company/loan/liquibase/changelog.xml'),
    includeMode: 'INCLUDE_ALL',
    includeTargets: [{
      path: 'com/company/loan/liquibase/changelog',
      includeAll: true,
      relativeToChangelogFile: false,
    }],
    generatedDirectory: 'loan/src/main/resources/com/company/loan/liquibase/changelog',
  }],
  entities: [{
    artifactId: 'entity-loan',
    moduleId: 'loan',
    className: 'LoanApp',
    qualifiedName: 'com.company.loan.entity.LoanApp',
    entityType: 'entity',
    entityName: 'loan_LoanApp',
    tableName: 'LOAN_LOAN_APP',
    storeName: 'main',
    idType: 'uuid',
    idColumnName: 'ID',
    databaseView: false,
    ddlMode: 'CREATE_AND_DROP',
    sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
    attributes: [
      {
        artifactId: 'entity-loan:applicationNo',
        name: 'applicationNo',
        javaType: 'String',
        columnName: 'APPLICATION_NO',
        nullable: false,
        unique: false,
        persistent: true,
        association: false,
        moneyCandidate: false,
        comment: 'Stable external application identifier',
        jmixProperty: true,
        dependsOnProperties: ['employee'],
        validations: [{
          type: 'size',
          value: '4',
          value2: '40',
          message: 'Application number must be 4–40 characters',
          groups: ['com.company.loan.validation.ApplicationChecks'],
        }],
        unmanagedAnnotations: ['LoanBusinessKey'],
      },
      {
        artifactId: 'entity-loan:loanAmount',
        name: 'loanAmount',
        javaType: 'BigDecimal',
        columnName: 'LOAN_AMOUNT',
        nullable: false,
        unique: false,
        persistent: true,
        association: false,
        moneyCandidate: true,
      },
      {
        artifactId: 'entity-loan:employee',
        name: 'employee',
        javaType: 'com.company.hr.entity.Employee',
        columnName: 'EMPLOYEE_ID',
        nullable: false,
        unique: false,
        persistent: true,
        association: true,
        associationDetails: {
          associationType: 'manyToOne',
          relatedEntity: 'com.company.hr.entity.Employee',
          relatedTableName: 'EMPLOYEE',
          relatedIdColumnName: 'ID',
          relatedIdType: 'uuid',
          joinColumnName: 'EMPLOYEE_ID',
          cascade: [],
          fetch: 'lazy',
          collectionType: 'list',
          crossDataStore: false,
          orphanRemoval: false,
          composition: false,
        },
        moneyCandidate: false,
      },
      {
        artifactId: 'entity-loan:primarySchedule',
        name: 'primarySchedule',
        javaType: 'com.company.loan.entity.LoanSchedule',
        columnName: 'PRIMARY_SCHEDULE_ID',
        nullable: true,
        unique: false,
        persistent: true,
        association: true,
        associationDetails: {
          associationType: 'manyToOne',
          relatedEntity: 'com.company.loan.entity.LoanSchedule',
          relatedTableName: 'LOAN_SCHEDULE',
          relatedIdColumnName: 'ID',
          relatedIdType: 'uuid',
          joinColumnName: 'PRIMARY_SCHEDULE_ID',
          cascade: [],
          fetch: 'lazy',
          collectionType: 'list',
          crossDataStore: false,
          orphanRemoval: false,
          composition: false,
        },
        moneyCandidate: false,
      },
      {
        artifactId: 'entity-loan:exclusiveSchedule',
        name: 'exclusiveSchedule',
        javaType: 'com.company.loan.entity.LoanSchedule',
        columnName: 'EXCLUSIVE_SCHEDULE_ID',
        nullable: true,
        unique: true,
        persistent: true,
        association: true,
        associationDetails: {
          associationType: 'oneToOne',
          relatedEntity: 'com.company.loan.entity.LoanSchedule',
          relatedTableName: 'LOAN_SCHEDULE',
          relatedIdColumnName: 'ID',
          relatedIdType: 'uuid',
          joinColumnName: 'EXCLUSIVE_SCHEDULE_ID',
          cascade: [],
          fetch: 'eager',
          collectionType: 'list',
          crossDataStore: false,
          orphanRemoval: false,
          composition: false,
        },
        moneyCandidate: false,
      },
      {
        artifactId: 'entity-loan:scheduleProfile',
        name: 'scheduleProfile',
        javaType: 'com.company.loan.entity.LoanSchedule',
        columnName: 'SCHEDULE_PROFILE',
        nullable: true,
        unique: false,
        persistent: true,
        association: true,
        associationDetails: {
          associationType: 'oneToOne',
          relatedEntity: 'com.company.loan.entity.LoanSchedule',
          relatedTableName: 'LOAN_SCHEDULE',
          relatedIdColumnName: 'ID',
          relatedIdType: 'uuid',
          mappedBy: 'loanApp',
          cascade: [],
          fetch: 'lazy',
          collectionType: 'list',
          crossDataStore: false,
          orphanRemoval: false,
          composition: false,
        },
        moneyCandidate: false,
      },
    ],
    traits: ['standardEntity', 'softDelete'],
    extendsClass: 'com.company.shared.BaseRecord',
    implementsInterfaces: ['com.company.shared.Approvable'],
    lifecycleCallbacks: ['prePersist', 'preUpdate'],
    entityListeners: ['com.company.loan.listener.LoanAuditListener'],
    inheritedAttributes: [{
      declaredBy: 'com.company.shared.BaseRecord',
      depth: 1,
      attribute: {
        artifactId: 'entity-base-record:branchCode',
        name: 'branchCode',
        javaType: 'String',
        columnName: 'BRANCH_CODE',
        nullable: false,
        unique: false,
        persistent: true,
        association: false,
        moneyCandidate: false,
      },
    }],
    inheritedTraits: [{
      trait: 'hasTenantId',
      declaredBy: 'com.company.shared.BaseRecord',
      depth: 1,
    }],
    migrationCoverage: 'COVERED',
    migrationArtifactIds: ['schema-loan-app'],
  }, {
    artifactId: 'entity-loan-schedule',
    moduleId: 'loan',
    className: 'LoanSchedule',
    qualifiedName: 'com.company.loan.entity.LoanSchedule',
    entityType: 'entity',
    entityName: 'loan_LoanSchedule',
    tableName: 'LOAN_SCHEDULE',
    storeName: 'main',
    idType: 'uuid',
    idColumnName: 'ID',
    databaseView: false,
    ddlMode: 'CREATE_AND_DROP',
    sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanSchedule.java'),
    attributes: [{
      artifactId: 'entity-loan-schedule:installmentNo',
      name: 'installmentNo',
      javaType: 'Integer',
      columnName: 'INSTALLMENT_NO',
      nullable: false,
      unique: false,
      persistent: true,
      association: false,
      moneyCandidate: false,
    }, {
      artifactId: 'entity-loan-schedule:loanApp',
      name: 'loanApp',
      javaType: 'com.company.loan.entity.LoanApp',
      columnName: 'LOAN_APP_ID',
      nullable: true,
      unique: true,
      persistent: true,
      association: true,
      associationDetails: {
        associationType: 'oneToOne',
        relatedEntity: 'com.company.loan.entity.LoanApp',
        relatedTableName: 'LOAN_LOAN_APP',
        relatedIdColumnName: 'ID',
        relatedIdType: 'uuid',
        joinColumnName: 'LOAN_APP_ID',
        cascade: [],
        fetch: 'lazy',
        collectionType: 'list',
        crossDataStore: false,
        orphanRemoval: false,
        composition: false,
      },
      moneyCandidate: false,
    }, {
      artifactId: 'entity-loan-schedule:primaryApplications',
      name: 'primaryApplications',
      javaType: 'java.util.List<com.company.loan.entity.LoanApp>',
      columnName: 'PRIMARY_APPLICATIONS',
      nullable: true,
      unique: false,
      persistent: true,
      association: true,
      associationDetails: {
        associationType: 'oneToMany',
        relatedEntity: 'com.company.loan.entity.LoanApp',
        relatedTableName: 'LOAN_LOAN_APP',
        relatedIdColumnName: 'ID',
        relatedIdType: 'uuid',
        mappedBy: 'primarySchedule',
        cascade: [],
        fetch: 'lazy',
        collectionType: 'list',
        crossDataStore: false,
        orphanRemoval: false,
        composition: false,
      },
      moneyCandidate: false,
    }],
    traits: [],
    implementsInterfaces: [],
    lifecycleCallbacks: [],
    entityListeners: [],
    inheritedAttributes: [],
    inheritedTraits: [],
    migrationCoverage: 'COVERED',
    migrationArtifactIds: ['schema-loan-app'],
  }, {
    artifactId: 'entity-employee',
    moduleId: 'hr',
    className: 'Employee',
    qualifiedName: 'com.company.hr.entity.Employee',
    entityType: 'entity',
    entityName: 'hr_Employee',
    tableName: 'EMPLOYEE',
    storeName: 'main',
    idType: 'uuid',
    idColumnName: 'ID',
    databaseView: false,
    ddlMode: 'DISABLED',
    sourceLocator: locator('hr/src/main/java/com/company/hr/entity/Employee.java'),
    attributes: [
      {
        artifactId: 'entity-employee:employeeNo',
        name: 'employeeNo',
        javaType: 'String',
        columnName: 'EMPLOYEE_NO',
        nullable: false,
        unique: true,
        persistent: true,
        association: false,
        moneyCandidate: false,
      },
    ],
    traits: [],
    implementsInterfaces: [],
    lifecycleCallbacks: [],
    entityListeners: [],
    inheritedAttributes: [],
    inheritedTraits: [],
    migrationCoverage: 'DISABLED',
    migrationArtifactIds: [],
  }, {
    artifactId: 'entity-payroll-projection',
    moduleId: 'payroll',
    className: 'PayrollProjection',
    qualifiedName: 'com.company.payroll.entity.PayrollProjection',
    entityType: 'dto',
    entityName: 'payroll_PayrollProjection',
    tableName: '',
    storeName: 'main',
    idType: 'uuid',
    idColumnName: 'ID',
    databaseView: false,
    ddlMode: 'DISABLED',
    sourceLocator: locator('payroll/src/main/kotlin/com/company/payroll/entity/PayrollProjection.kt'),
    attributes: [{
      artifactId: 'entity-payroll-projection:employeeNo',
      name: 'employeeNo',
      javaType: 'String',
      columnName: 'EMPLOYEE_NO',
      nullable: true,
      unique: false,
      persistent: false,
      association: false,
      moneyCandidate: false,
    }],
    traits: [],
    implementsInterfaces: [],
    lifecycleCallbacks: [],
    entityListeners: [],
    inheritedAttributes: [],
    inheritedTraits: [],
    migrationCoverage: 'DISABLED',
    migrationArtifactIds: [],
  }],
  repositories: [{
    artifactId: 'repository-loan-app',
    moduleId: 'loan',
    interfaceName: 'LoanAppRepository',
    qualifiedName: 'com.company.loan.repository.LoanAppRepository',
    entityQualifiedName: 'com.company.loan.entity.LoanApp',
    idType: 'UUID',
    sourceLanguage: 'java',
    sourceLocator: locator(
      'loan/src/main/java/com/company/loan/repository/LoanAppRepository.java',
    ),
    config: {
      enabled: true,
      interfaceName: 'LoanAppRepository',
      applyConstraints: true,
      useNamedParameters: true,
      methods: [{
        name: 'findByProcessState',
        returnType: 'List<LoanApp>',
        parameters: [{
          name: 'processState',
          type: 'String',
          nullable: false,
          role: 'value',
        }],
        queryType: 'derived',
        queryProperties: [],
        queryHints: [],
      }],
    },
    methodEvidence: [{
      sourceSignature: 'findByProcessState(String)',
      editable: true,
      methodIndex: 0,
    }],
  }],
  changelogs: [{
    artifactId: 'liquibase-loan-root',
    moduleId: 'loan',
    relativePath: 'loan/src/main/resources/com/company/loan/liquibase/changelog.xml',
    sourceLocator: locator('loan/src/main/resources/com/company/loan/liquibase/changelog.xml'),
    root: true,
    changeSetCount: 0,
    includes: [{
      path: 'com/company/loan/liquibase/changelog',
      includeAll: true,
      relativeToChangelogFile: false,
    }],
    tables: [],
    containsRawSql: false,
  }],
  physicalSchemas: [{
    storeId: 'loan:main',
    moduleId: 'loan',
    complete: true,
    changelogPaths: [
      'loan/src/main/resources/com/company/loan/liquibase/changelog.xml',
      'loan/src/main/resources/com/company/loan/liquibase/changelog/010-init.xml',
    ],
    tables: [{
      name: 'LOAN_LOAN_APP',
      columns: [{
        name: 'ID',
        type: 'UUID',
        nullable: false,
        unique: true,
        primaryKey: true,
      }, {
        name: 'PRIMARY_SCHEDULE_ID',
        type: 'UUID',
        nullable: true,
        unique: false,
        primaryKey: false,
      }, {
        name: 'EXCLUSIVE_SCHEDULE_ID',
        type: 'UUID',
        nullable: true,
        unique: true,
        primaryKey: false,
      }],
      foreignKeys: [{
        constraintName: 'FK_LOAN_LOAN_APP_PRIMARY_SCHEDULE',
        baseColumnNames: 'PRIMARY_SCHEDULE_ID',
        referencedTableName: 'LOAN_SCHEDULE',
        referencedColumnNames: 'ID',
      }],
      uniqueConstraints: [{
        name: 'UQ_LOAN_LOAN_APP_EXCLUSIVE_SCHEDULE',
        columns: ['EXCLUSIVE_SCHEDULE_ID'],
      }],
      sourcePaths: ['loan/src/main/resources/com/company/loan/liquibase/changelog/010-init.xml'],
    }, {
      name: 'LOAN_SCHEDULE',
      columns: [{
        name: 'ID',
        type: 'UUID',
        nullable: false,
        unique: true,
        primaryKey: true,
      }, {
        name: 'LOAN_APP_ID',
        type: 'UUID',
        nullable: true,
        unique: true,
        primaryKey: false,
      }],
      foreignKeys: [{
        constraintName: 'FK_LOAN_SCHEDULE_LOAN_APP',
        baseColumnNames: 'LOAN_APP_ID',
        referencedTableName: 'LOAN_LOAN_APP',
        referencedColumnNames: 'ID',
      }],
      uniqueConstraints: [{
        name: 'UQ_LOAN_SCHEDULE_LOAN_APP',
        columns: ['LOAN_APP_ID'],
      }],
      sourcePaths: ['loan/src/main/resources/com/company/loan/liquibase/changelog/010-init.xml'],
    }],
  }],
  drifts: [
    {
      id: 'development-drift-application-no',
      kind: 'COLUMN_MISSING',
      severity: 'ERROR',
      safety: 'SAFE',
      confidence: 'HIGH',
      moduleId: 'loan',
      storeId: 'loan:main',
      entityArtifactId: 'entity-loan',
      entitySourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      tableName: 'LOAN_LOAN_APP',
      columnName: 'APPLICATION_NO',
      message: 'LOAN_LOAN_APP.APPLICATION_NO is mapped by LoanApp but is absent from Liquibase.',
      suggestion: {
        changeType: 'addColumn',
        tableName: 'LOAN_LOAN_APP',
        columnName: 'APPLICATION_NO',
        columnType: 'VARCHAR(255)',
        nullable: false,
        columns: [],
        columnNames: [],
      },
    },
    {
      id: 'development-drift-loan-amount',
      kind: 'COLUMN_MISSING',
      severity: 'ERROR',
      safety: 'SAFE',
      confidence: 'HIGH',
      moduleId: 'loan',
      storeId: 'loan:main',
      entityArtifactId: 'entity-loan',
      entitySourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      tableName: 'LOAN_LOAN_APP',
      columnName: 'LOAN_AMOUNT',
      message: 'LOAN_LOAN_APP.LOAN_AMOUNT is mapped by LoanApp but is absent from Liquibase.',
      suggestion: {
        changeType: 'addColumn',
        tableName: 'LOAN_LOAN_APP',
        columnName: 'LOAN_AMOUNT',
        columnType: 'DECIMAL(19,2)',
        nullable: false,
        columns: [],
        columnNames: [],
      },
    },
  ],
  findings: [
    {
      severity: 'WARNING',
      code: 'SCHEMA_BUSINESS_IDENTIFIER_NOT_UNIQUE',
      message: 'LoanApp.applicationNo looks like a business identifier but has no visible unique mapping.',
      moduleId: 'loan',
      sourceLocator: locator('loan/src/main/java/com/company/loan/entity/LoanApp.java'),
      entityArtifactId: 'entity-loan',
    },
    {
      severity: 'INFO',
      code: 'SCHEMA_SOURCE_COVERAGE',
      message: 'Source changelog coverage is available; connect a runtime database to perform a live entity/schema diff.',
      moduleId: 'loan',
    },
  ],
  issues: [],
}
