export type FlowUiBindingKind = 'FIELD' | 'COLLECTION' | 'LOADER'

export interface FlowUiCatalogItem {
  tag: string
  label: string
  category: 'Layout' | 'Input' | 'Data' | 'Navigation' | 'Display' | 'Structure'
  description: string
  childCapable?: boolean
  binding?: FlowUiBindingKind
  defaultAttributes?: Record<string, string>
  allowedParents?: string[]
  keywords?: string[]
}

/**
 * Core FlowUI elements that can be emitted without an add-on namespace.
 * Add-on components are discovered from project metadata in a later catalog
 * layer; they must never be guessed into an enterprise descriptor.
 */
export const flowUiComponentCatalog: FlowUiCatalogItem[] = [
  {
    tag: 'vbox',
    label: 'Vertical layout',
    category: 'Layout',
    description: 'Stacks children vertically and stretches to available width.',
    childCapable: true,
    defaultAttributes: { width: '100%' },
    keywords: ['column', 'vertical', 'container'],
  },
  {
    tag: 'hbox',
    label: 'Horizontal layout',
    category: 'Layout',
    description: 'Places actions or fields in a responsive horizontal row.',
    childCapable: true,
    defaultAttributes: { width: '100%', wrap: 'true' },
    keywords: ['row', 'buttons', 'horizontal', 'container'],
  },
  {
    tag: 'flexLayout',
    label: 'Flex layout',
    category: 'Layout',
    description: 'Flexible wrapping layout for adaptive screens.',
    childCapable: true,
    defaultAttributes: { width: '100%', flexWrap: 'WRAP' },
    keywords: ['responsive', 'flex', 'wrap'],
  },
  {
    tag: 'formLayout',
    label: 'Responsive form',
    category: 'Layout',
    description: 'Form layout for labeled entity fields and responsive columns.',
    childCapable: true,
    defaultAttributes: { width: '100%', autoResponsive: 'true' },
    keywords: ['form', 'responsive', 'fields'],
  },
  {
    tag: 'gridLayout',
    label: 'Grid layout',
    category: 'Layout',
    description: 'Explicit row and column positioning for structured content.',
    childCapable: true,
    defaultAttributes: { width: '100%' },
    keywords: ['grid', 'columns', 'rows'],
  },
  {
    tag: 'split',
    label: 'Split panel',
    category: 'Layout',
    description: 'Resizable two-pane layout.',
    childCapable: true,
    defaultAttributes: { width: '100%', height: '100%' },
    keywords: ['splitter', 'master detail'],
  },
  {
    tag: 'scroller',
    label: 'Scroller',
    category: 'Layout',
    description: 'Scrollable container for content that can exceed the viewport.',
    childCapable: true,
    defaultAttributes: { width: '100%', height: '100%' },
    keywords: ['scroll', 'overflow'],
  },
  {
    tag: 'details',
    label: 'Details section',
    category: 'Layout',
    description: 'Collapsible group for advanced or secondary fields.',
    childCapable: true,
    defaultAttributes: { width: '100%', opened: 'true' },
    keywords: ['collapse', 'section'],
  },
  {
    tag: 'tabSheet',
    label: 'Tab sheet',
    category: 'Navigation',
    description: 'Groups complex screen sections into tabs.',
    childCapable: true,
    defaultAttributes: { width: '100%' },
    keywords: ['tabs', 'pages'],
  },
  {
    tag: 'tab',
    label: 'Tab',
    category: 'Structure',
    description: 'A content page inside a tab sheet.',
    childCapable: true,
    defaultAttributes: { label: 'New tab' },
    allowedParents: ['tabSheet'],
  },
  {
    tag: 'accordion',
    label: 'Accordion',
    category: 'Navigation',
    description: 'Compact collapsible sections for dense enterprise screens.',
    childCapable: true,
    defaultAttributes: { width: '100%' },
    keywords: ['collapse', 'panels'],
  },
  {
    tag: 'textField',
    label: 'Text field',
    category: 'Input',
    description: 'Single-line text input with optional entity binding.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['string', 'name'],
  },
  {
    tag: 'textArea',
    label: 'Text area',
    category: 'Input',
    description: 'Multi-line input for notes and descriptions.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%', minHeight: '8em' },
    keywords: ['notes', 'description', 'multiline'],
  },
  {
    tag: 'emailField',
    label: 'Email field',
    category: 'Input',
    description: 'Email-aware text input.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['mail'],
  },
  {
    tag: 'passwordField',
    label: 'Password field',
    category: 'Input',
    description: 'Masked text input. Never bind persisted secrets without review.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['secret', 'credential'],
  },
  {
    tag: 'integerField',
    label: 'Integer field',
    category: 'Input',
    description: 'Whole-number input.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['number', 'count'],
  },
  {
    tag: 'numberField',
    label: 'Number field',
    category: 'Input',
    description: 'Floating-point numeric input; avoid for money.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['double', 'numeric'],
  },
  {
    tag: 'bigDecimalField',
    label: 'Decimal / money field',
    category: 'Input',
    description: 'Exact decimal input recommended for payroll and finance.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['money', 'currency', 'amount', 'decimal'],
  },
  {
    tag: 'datePicker',
    label: 'Date picker',
    category: 'Input',
    description: 'Date input with locale-aware picker.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['calendar', 'localdate'],
  },
  {
    tag: 'dateTimePicker',
    label: 'Date and time',
    category: 'Input',
    description: 'Combined date and time input.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['timestamp', 'datetime'],
  },
  {
    tag: 'timePicker',
    label: 'Time picker',
    category: 'Input',
    description: 'Time-of-day input.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['time'],
  },
  {
    tag: 'checkbox',
    label: 'Checkbox',
    category: 'Input',
    description: 'Boolean value input.',
    binding: 'FIELD',
    keywords: ['boolean', 'yes no'],
  },
  {
    tag: 'comboBox',
    label: 'Combo box',
    category: 'Input',
    description: 'Selectable scalar or enum values.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['select', 'enum'],
  },
  {
    tag: 'radioButtonGroup',
    label: 'Radio group',
    category: 'Input',
    description: 'Visible mutually-exclusive choices.',
    binding: 'FIELD',
    keywords: ['options', 'enum'],
  },
  {
    tag: 'entityPicker',
    label: 'Entity picker',
    category: 'Input',
    description: 'Entity association picker with lookup actions.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['relation', 'association', 'lookup'],
  },
  {
    tag: 'entityComboBox',
    label: 'Entity combo box',
    category: 'Input',
    description: 'Entity selection using a dropdown.',
    binding: 'FIELD',
    defaultAttributes: { width: '100%' },
    keywords: ['relation', 'association'],
  },
  {
    tag: 'fileUploadField',
    label: 'File upload',
    category: 'Input',
    description: 'Single-file upload field.',
    defaultAttributes: { width: '100%' },
    keywords: ['document', 'attachment', 'upload'],
  },
  {
    tag: 'dataGrid',
    label: 'Data grid',
    category: 'Data',
    description: 'Lazy enterprise table bound to a collection container.',
    childCapable: true,
    binding: 'COLLECTION',
    defaultAttributes: { width: '100%', minHeight: '16em' },
    keywords: ['table', 'list', 'rows'],
  },
  {
    tag: 'treeDataGrid',
    label: 'Tree data grid',
    category: 'Data',
    description: 'Hierarchical collection grid.',
    childCapable: true,
    binding: 'COLLECTION',
    defaultAttributes: { width: '100%', minHeight: '16em' },
    keywords: ['tree', 'hierarchy', 'table'],
  },
  {
    tag: 'genericFilter',
    label: 'Generic filter',
    category: 'Data',
    description: 'User-configurable filter connected to a collection loader.',
    binding: 'LOADER',
    defaultAttributes: { width: '100%' },
    keywords: ['search', 'query', 'criteria'],
  },
  {
    tag: 'simplePagination',
    label: 'Pagination',
    category: 'Data',
    description: 'Paging controls connected to a collection loader.',
    binding: 'LOADER',
    keywords: ['pages', 'loader'],
  },
  {
    tag: 'columns',
    label: 'Grid columns',
    category: 'Structure',
    description: 'Column collection inside a data grid.',
    childCapable: true,
    allowedParents: ['dataGrid', 'treeDataGrid'],
  },
  {
    tag: 'column',
    label: 'Grid column',
    category: 'Structure',
    description: 'Entity property column inside grid columns.',
    childCapable: true,
    allowedParents: ['columns'],
  },
  {
    tag: 'actions',
    label: 'Actions collection',
    category: 'Structure',
    description: 'Declarative actions for a view or action-aware component.',
    childCapable: true,
    allowedParents: ['view', 'dataGrid', 'treeDataGrid', 'entityPicker', 'entityComboBox'],
  },
  {
    tag: 'action',
    label: 'Action',
    category: 'Structure',
    description: 'Standard or custom declarative action.',
    defaultAttributes: { type: 'list_create' },
    allowedParents: ['actions'],
  },
  {
    tag: 'formItem',
    label: 'Form item',
    category: 'Structure',
    description: 'Labeled wrapper inside a form layout.',
    childCapable: true,
    defaultAttributes: { label: 'Field' },
    allowedParents: ['formLayout'],
  },
  {
    tag: 'button',
    label: 'Button',
    category: 'Navigation',
    description: 'Action or controller-handler trigger.',
    defaultAttributes: { text: 'Button' },
    keywords: ['command', 'submit'],
  },
  {
    tag: 'span',
    label: 'Text',
    category: 'Display',
    description: 'Short text or message.',
    defaultAttributes: { text: 'Text' },
    keywords: ['label', 'caption'],
  },
  {
    tag: 'h1',
    label: 'Heading 1',
    category: 'Display',
    description: 'Primary accessible page heading.',
    defaultAttributes: { text: 'Heading' },
    keywords: ['title'],
  },
  {
    tag: 'h2',
    label: 'Heading 2',
    category: 'Display',
    description: 'Accessible section heading.',
    defaultAttributes: { text: 'Section' },
    keywords: ['title'],
  },
  {
    tag: 'icon',
    label: 'Icon',
    category: 'Display',
    description: 'Theme icon for visual status or emphasis.',
    defaultAttributes: { icon: 'CHECK' },
  },
  {
    tag: 'image',
    label: 'Image',
    category: 'Display',
    description: 'Image with an accessibility text alternative.',
    defaultAttributes: { alt: 'Image' },
    keywords: ['picture', 'media'],
  },
  {
    tag: 'progressBar',
    label: 'Progress bar',
    category: 'Display',
    description: 'Determinate or indeterminate progress indicator.',
    defaultAttributes: { width: '100%' },
    keywords: ['loading', 'status'],
  },
]

export const flowUiCatalogCategories = [
  'Layout',
  'Input',
  'Data',
  'Navigation',
  'Display',
  'Structure',
] as const
